apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: griddog

resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - backend.yaml
  - java-service.yaml
  - express-service.yaml
  - frontend.yaml
