# Fill in IPs from: terraform output
# Run: cd deploy/vm/terraform && terraform output

[nginx]
griddog-nginx ansible_host=54.254.196.99

[frontend]
griddog-frontend ansible_host=172.31.66.28 ansible_ssh_common_args='-J ubuntu@54.254.196.99 -i ~/.ssh/griddog-keypair.pem'

[app]
griddog-app ansible_host=172.31.66.214 ansible_ssh_common_args='-J ubuntu@54.254.196.99 -i ~/.ssh/griddog-keypair.pem'

[databases]
griddog-databases ansible_host=172.31.66.145 ansible_ssh_common_args='-J ubuntu@54.254.196.99 -i ~/.ssh/griddog-keypair.pem'
